ipc_accueilListing:
    path: /index
    defaults: { _controller: IpcListingBundle:Listing:index}
    requirements:
        _method: GET

ipc_listing:
    path: /affiche/{page}
    defaults: { _controller: IpcListingBundle:Listing:afficheListing, page:'0'}
    requirements:
        page: \d+
        _method: GET

ipc_modifieListing:
    path: /modification
    defaults: { _controller: IpcListingBundle:Listing:modifieRequete }

ipc_trie_donnees:
    path: /ajaxTrieDonnees
    defaults: { _controller: IpcListingBundle:Listing:ajaxTrieDonnees }
