parameters:
#    ipc_listing.example.class: Ipc\ListingBundle\Example

services:
#    ipc_listing.example:
#        class: %ipc_listing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
