<?php

namespace Ipc\ProgBundle\Entity;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityRepository;

/**
 * DonneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneeRepository extends EntityRepository
{
    // Fonction qui retourne un tableau de type : GenreCategorieModuleMessage (exemple 01EX1216)
    // Permet de checked qu'une donnée à insérer en base contient des informations existante
    public function myCreateTab() {
        return $this->getEntityManager()->createQueryBuilder()
                    ->select('m.id','g.numeroGenre','m.categorie','m.numeroModule','m.numeroMessage')
                    ->from($this->_entityName,'m')
                    ->leftJoin('m.genre','g')
                    ->getQuery()
                    ->getArrayResult();
    }

    public function myFindAllListingV2() {
        return $this
            ->createQueryBuilder('m')
            ->select('m.id','m.message','m.categorie','m.numeroModule','m.numeroMessage','m.intituleModule','g.numeroGenre')
            ->leftJoin('m.genre','g')
            ->getQuery()
            ->getArrayResult();
    }


	public function findLastData() {
		$qb = $this->createQueryBuilder('d');
		$qb	->orderBy('d.id', 'DESC')
			->setFirstResult(0)
			->setMaxResults(1);
		return $qb->getQuery()->getOneOrNullResult();
	}


    public function findLastDataForLoc($id_localisation) {
        $qb = $this->createQueryBuilder('d');
        $qb ->where('d.localisation_id = :id_loc')
			->orderBy('d.id', 'DESC')
			->setParameter('id_loc', $id_localisation)
            ->setFirstResult(0)
            ->setMaxResults(1);
        return $qb->getQuery()->getOneOrNullResult();
    }


}
