;var $selectCourant,$selectClient;function addCompteRequest(e){attente();var t=$("#lien_url_ajax").attr("data-urlGetRequetesPerso"),i=$("#requeteClient").is(":checked");if(i==!0){if($selectCourant==null){$selectCourant=$("#selectRegPerso").html()};if($selectClient==null){$.ajax({url:t,method:"get",data:"nomUtilisateur=Client&page="+e,timeout:10000}).done(function(t,a){var i=JSON.parse(t);$selectClient="<option value='noselected' disabled selected style='color:blue'>"+traduire("select.requetes_client.titre."+e)+"</option>";$.each(i,function(e,t){$selectClient=$selectClient+"<option value='"+t+"'>"+t+"</option>"});$("#selectRegPerso").html($selectClient);fin_attente()}).fail(function(e,t,a){alert("Erreur "+a);fin_attente()})}
else{$("#selectRegPerso").html($selectClient);fin_attente()}}
else{if($selectClient==null){$selectClient=$("#selectRegPerso").html()};if($selectCourant==null){var a="";$.ajax({url:t,method:"get",data:"nomUtilisateur="+a+"&page="+e,timeout:10000}).done(function(t,a){var i=JSON.parse(t);$selectCourant="<option value='noselected' disabled selected style='color:blue'>"+traduire("select.requetes_perso.titre."+e)+"</option>";$.each(i,function(e,t){$selectCourant=$selectCourant+"<option value='"+t+"'>"+t+"</option>"});$("#selectRegPerso").html($selectCourant);fin_attente()}).fail(function(e,t,a){alert("Erreur "+a);fin_attente()})}
else{$("#selectRegPerso").html($selectCourant);fin_attente()}}};function saveRequest(){var e="",t=$("#choixPage_requetePerso").val();if(t=="listing"){e=$("#lien_url_ajax").attr("data-urlSaveListingPersoRequest")}
else if(t=="graphique"){e=$("#lien_url_ajax").attr("data-urlSaveGraphiquePersoRequest")};var a=$("#chkRequeteClient").prop("checked");$nameRequest=$("#intituleRequetePerso").val();if(checkValue($nameRequest)){attente();$.ajax({url:e,method:"GET",data:{nom:$nameRequest,requeteClient:a},timeout:10000}).done(function(e,t){$("#ajout_requete_perso").addClass("cacher");$("#messageValidation").html("Requête enregistrée");$("#messageValidation").removeClass("cacher");setTimeout(function(){location.reload()},500)}).fail(function(e,t,a){alert("Erreur "+a);fin_attente()})};return 0};function closeRequest(){removeShadow("popup");activateLinks();$("#lightboxSmall").addClass("cacher");$("#choixPage_requetePerso").val("");$("#intituleRequetePerso").val("");return};function checkValue(e){var t=e.match(/^[a-zA-Z0-9\s]+$/);if(t!==null){if(e.length>40){alert("40 caractères maximum autorisés ("+e.length+" actuellement.)")}
else{return!0}}
else{alert("Vous avez entré des caractères incorrects.\nMerci de n'utiliser que des chiffres, des lettres et des espaces.");return!1}};function supprimeRequetePerso(e){attente();addShadow("popup");desactivateLinks();var a="",i=$("#requeteClient").is(":checked");if(i==!0){a="Client"};if(e=="listing"){$url=$("#lien_url_ajax").attr("data-urlDeleteListingPersoRequest")}
else if(e=="graphique"){$url=$("#lien_url_ajax").attr("data-urlDeleteGraphiquePersoRequest")};var t=$("#selectRegPerso option:selected").val();if((t!="noselected")&&($("#selectRegPerso option:selected").index()!=0)){$.ajax({url:$url,method:"get",data:"nom="+t+"&compte="+a,timeout:10000}).done(function(e,t){$("#ajout_requete_perso").addClass("cacher");$("#messageValidation").html("Requête supprimée");$("#messageValidation").removeClass("cacher");$("#lightboxSmall").removeClass("cacher");setTimeout(function(){location.reload()},500)}).fail(function(e,t,a){alert("Erreur "+a);activateLinks();removeShadow("popup");fin_attente()})}
else{activateLinks();removeShadow("popup");fin_attente()}};function selectRequest(){attente();var i=$("#requeteClient").is(":checked"),e="";if(i==!0){e="Client"};var t=$("#selectRegPerso").attr("data-url"),a=$("#selectRegPerso option:selected").val();if($("#selectRegPerso option:selected").index()!=0){$.ajax({url:t,method:"get",data:"nom="+a+"&compte="+e,timeout:10000}).done(function(e,t){var a=e.match(/^Erreur(.+?)$/);if(a!=null){alert("message "+a);fin_attente()}
else{location.reload()}}).fail(function(e,t,a){alert("Erreur "+a);fin_attente()})}
else{fin_attente()}};function creerRequetePerso(e){addShadow("popup");desactivateLinks();setTimeout(function(){$("#lightboxSmall").removeClass("cacher");$("#choixPage_requetePerso").val(e)},100)};function checkValidationPopup(){if($("#modificationRequete").val()!=""){closeLightBox()}};function changeListeMessagesSize(e){if(e=="in"){$("#messages").attr("size",5)};if(e=="out"){$("#messages").attr("size",1);$("#messageDeLaListe").text("")}};function afficheListeMessage(){$message=$("#messages option:selected").text();$("#messageDeLaListe").text($message)};function changeTypeListe(e){attente();$valeur=0;if($("#maxListe").is(":checked")){$valeur=1};$urlRequest=$("#maxListe").attr("data-url");$.ajax({type:"post",url:$urlRequest,data:"liste_complete="+$valeur,success:function(t,a){if(e=="graphique"){selection("graphique","genre",!1)}
else if(e=="listing"){selection("listing","genre",!1)};if($valeur==1){$("#maxListe").prop("checked",!0)}
else{$("#maxListe").prop("checked",!1)};fin_attente()},error:function(e,t,a){alert("error");fin_attente()}})};