parameters:
#    ipc_graphique.example.class: Ipc\GraphiqueBundle\Example

services:
#    ipc_graphique.example:
#        class: %ipc_graphique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
