parameters:
#    ipc_analyse.example.class: Ipc\AnalyseBundle\Example

services:
#    ipc_analyse.example:
#        class: %ipc_analyse.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
