parameters:
#    ipc_outils.example.class: Ipc\OutilsBundle\Example

services:
#    ipc_outils.example:
#        class: %ipc_outils.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
