<?php

namespace Ipc\ConfigurationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigModbusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigModbusRepository extends EntityRepository
{
}
