<?php

namespace Ipc\ConfigurationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeteRepository extends EntityRepository
{
	public function myfindByCreateur($createur) {
		return $this->createQueryBuilder('r')
		->where('r.createur = :createur')
		->andWhere('r.compte is null')
		->setParameter('createur', $createur)
		->getQuery()
		->getResult();
	}
}
